<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/account.php
// Date: 2016-10-04 08:32:48
return array(
    'activated'                         => 'Your account is activated!',
    'confirmation_required'             => 'You\'r almost done! Please, check out your email box.',
    'create'                            => 'Create an account',
    'email_label'                       => 'E-Mail address',
    'email_placeholder'                 => 'Your email',
    'email_title'                       => 'Email',
    'first_name_label'                  => 'First name',
    'first_name_placeholder'            => 'Your first name',
    'full_name_title'                   => 'Full name',
    'last_name_label'                   => 'Last name',
    'last_name_placeholder'             => 'Your last name',
    'name_placeholder'                  => 'Your account name',
    'new_title'                         => 'New account',
    'nickname_label'                    => 'Unique name',
    'password_confirmation_label'       => 'Password confirmation',
    'password_confirmation_placeholder' => 'Type your password again',
    'password_label'                    => 'Password',
    'password_new_label'                => 'New password',
    'password_new_placeholder'          => 'Type a new password',
    'password_placeholder'              => 'Type your password',
    'password_reset_title'              => 'Reset password',
    'password_reset_url'                => 'Send Password Reset Link',
    'profile_update'                    => 'Update profile',
    'profile_updated'                   => 'Your profile have been updated.',
    'remember_label'                    => 'Remember me',
    'title'                             => 'Account|Accounts',
    'update'                            => 'Update account \':profile\'',
);