<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/auth.php
// Date: 2016-10-04 08:32:48
return array(
    'facebook_login'        => 'Via Facebook',
    'failed'                => 'These credentials do not match our records.',
    'github_login'          => 'Via Github',
    'google_login'          => 'Via Google',
    'login'                 => 'Login',
    'logout'                => 'Logout',
    'password_reset_forgot' => 'Forgot Your Password?',
    'throttle'              => 'Too many login attempts. Please try again in :seconds seconds.',
    'vkontakte_login'       => 'Via Vkontakte',
);