<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/blog.php
// Date: 2016-10-22 11:49:45
return array(
    'content_label'            => 'Post content',
    'content_placeholder'      => 'Post content',
    'is_post_published'        => 'Is post published?',
    'new_title'                => 'New blog post',
    'post'                     => 'Blog post|Blog posts',
    'post_status'              => 'Post status',
    'post_update'              => 'Update blog post',
    'preview_content_label'    => 'Post preview',
    'preview_image_label'      => 'Preview image',
    'preview_text' => array(
        'label' => 'Post preview',
    ),
    'preview_text_placeholder' => 'Preview content',
    'read_more_title'          => 'read more',
    'title'                    => 'Blog',
    'title_label'              => 'Post title',
    'title_placeholder'        => 'Title text',
);