<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/catalog.php
// Date: 2016-10-04 08:32:48
return array(
    'new_title'                      => 'New catalog product',
    'product'                        => 'Catalog product|Catalog products',
    'product_alias_name_label'       => 'Unique name in catalog',
    'product_alias_name_placeholder' => 'Name text',
    'product_characteristics'        => 'Characteristics',
    'product_filter'                 => 'Catalog filter|Catalog filters',
    'product_filter_category'        => 'Catalog filters category|Catalog filters categories',
    'product_images_update'          => 'Update \':product\' images',
    'product_information'            => 'All about product',
    'product_main_image_label'       => 'Product main image',
    'product_property'               => 'Catalog product property|Catalog product properties',
    'product_property_new_title'     => 'New catalog product property',
    'product_property_value_label'   => 'Value',
    'product_update'                 => 'Update catalog product',
    'property_update'                => 'Update \':property\' property|Update \':property\' properties',
    'title'                          => 'Catalog',
);