<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/category.php
// Date: 2016-10-04 08:32:48
return array(
    'new_title' => 'New category',
    'update'    => 'Update category',
);