<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/category.php
// Date: 2016-10-22 11:49:45
return array(
    'new_title'          => 'New category',
    'update'             => 'Update category',
    'visible_name_label' => 'Name to display',
);