<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/category.php
// Date: 2016-10-01 12:17:15
return array(
    'new_title' => 'New category',
    'update'    => 'Update category',
);