<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/feedback.php
// Date: 2016-09-29 14:29:00
return array(
    'from_name_label'             => 'Your name',
    'from_name_placeholder'       => 'Your name',
    'message_content_placeholder' => 'Message content',
    'message_content_title'       => 'Message',
    'message_update'              => 'Update contact message from',
    'request_from'                => 'Request from',
    'sender_email_placeholder'    => 'Sender E-Mail address',
    'sender_email_title'          => 'E-Mail address',
    'sender_name_placeholder'     => 'Sender name',
    'sender_name_title'           => 'Sender',
    'title'                       => 'Feedback',
);