<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/filter.php
// Date: 2016-10-04 08:32:48
return array(
    'catalog_category'     => 'Catalog category',
    'is_filter_disabled'   => 'Is filter disabled?',
    'left_property_label'  => '\'Left\' property value',
    'new_title'            => 'New filter',
    'right_property_label' => '\'Right\' property value',
    'state'                => 'Filter state',
    'title_label'          => 'Filter title',
    'title_placeholder'    => 'Title text',
    'type_label'           => 'Filter type',
    'update'               => 'Update filter',
);