<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/models.php
// Date: 2016-10-01 12:17:15
return array(
    'deleted' => ':Name model has been deleted.',
    'edit'    => 'Edit :Name model.',
    'saved'   => ':Name model have been saved.',
    'updated' => ':Name model have been updated.',
);