<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/models.php
// Date: 2016-10-04 08:32:48
return array(
    'deleted' => 'Model have been deleted.',
    'edit'    => 'Edit :Name model.',
    'saved'   => 'Model have been saved.',
    'updated' => 'Model have been updated.',
);