<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/pagination.php
// Date: 2016-10-22 11:49:45
return array(
    'next'     => 'Next &raquo;',
    'previous' => '&laquo; Previous',
);