<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/pagination.php
// Date: 2016-10-01 12:17:15
return array(
    'next'     => 'Next &raquo;',
    'previous' => '&laquo; Previous',
);