<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/pagination.php
// Date: 2016-10-04 08:32:48
return array(
    'next'     => 'Next &raquo;',
    'previous' => '&laquo; Previous',
);