<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/subscription.php
// Date: 2016-10-04 08:32:48
return array(
    'is_news_subscribed'  => 'Subscribe on news updates?',
    'is_posts_subscribed' => 'Subscribe on blog updates?',
    'update'              => 'Subscription management',
);