<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/en/task.php
// Date: 2016-10-22 11:49:45
return array(
    'content_label'       => 'Task text',
    'content_placeholder' => 'Task text',
    'new_title'           => 'New task',
    'title'               => 'Tasks',
    'title_label'         => 'Task label',
    'title_placeholder'   => 'Title text',
    'update'              => 'Update task',
);