<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/account.php
// Date: 2016-10-04 08:32:48
return array(
    'activated'                         => 'Ваша учётная запись активирована!',
    'confirmation_required'             => 'Вы почти у цели! Пожалуйста, проверьте Ваш email.',
    'create'                            => 'Создать учётную запись',
    'email_label'                       => 'Арес электронной почты',
    'email_placeholder'                 => 'Ваш адрес электронной почты',
    'email_title'                       => 'Email',
    'first_name_label'                  => 'Имя',
    'first_name_placeholder'            => 'Ваше имя',
    'full_name_title'                   => 'Полное имя',
    'last_name_label'                   => 'Фамилия',
    'last_name_placeholder'             => 'Ваша фамилия',
    'new_title'                         => 'Новая учётная запись',
    'nickname_label'                    => 'Уникальное имя',
    'password_confirmation_label'       => 'Подтверждение пароля',
    'password_confirmation_placeholder' => 'Повторите пароль',
    'password_label'                    => 'Пароль',
    'password_new_label'                => 'Новый пароль',
    'password_new_placeholder'          => 'Введите новый пароль',
    'password_placeholder'              => 'Введите пароль',
    'password_reset_title'              => 'Сбросить пароль',
    'password_reset_url'                => 'Отправить ссылку для восстановления пароля',
    'profile_update'                    => 'Обновить профиль',
    'profile_updated'                   => 'Ваш профиль обновлён.',
    'remember_label'                    => 'Запомнить меня',
    'title'                             => 'Учётная запись|Учётные записи',
    'update'                            => 'Обновить учётную запись \':profile\'',
);