<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/auth.php
// Date: 2016-09-29 14:29:00
return array(
    'facebook_login'        => 'Через Facebook',
    'failed'                => 'Имя пользователя и пароль не совпадают.',
    'github_login'          => 'Через Github',
    'google_login'          => 'Через Google',
    'login'                 => 'Войти',
    'logout'                => 'Выйти',
    'password_reset_forgot' => 'Забыли пароль?',
    'throttle'              => 'Слишком много попыток входа. Пожалуйста, попробуйте еще раз через :seconds секунд.',
    'vkontakte_login'       => 'Через Вконтакте',
);