<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/blog.php
// Date: 2016-10-01 12:17:15
return array(
    'content_label'         => 'Содержимое записи',
    'content_placeholder'   => 'Содержимое записи',
    'is_post_published'     => 'Запись опубликована?',
    'new_title'             => 'Новая запись блога',
    'post'                  => 'Запись блога|Записи блога',
    'post_status'           => 'Статус записи',
    'post_update'           => 'Обновить запись блога',
    'preview_content_label' => 'Preview записи',
    'preview_image_label'   => 'Изображение preview',
    'preview_text' => array(
        'label'       => 'Preview записи',
        'placeholder' => 'Содержимое preview',
    ),
    'read_more_title'       => 'читать далее',
    'title'                 => 'Блог',
    'title_label'           => 'Заголовок записи',
    'title_placeholder'     => 'Текст заголовка',
);