<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/catalog.php
// Date: 2016-10-01 12:17:15
return array(
    'new_title'                      => 'Новый товар каталога',
    'product'                        => 'Товар каталог|Товары каталога',
    'product_alias_name_label'       => 'Уникальное название в каталоге',
    'product_alias_name_placeholder' => 'Текст названия',
    'product_characteristics'        => 'Характеристики',
    'product_filter'                 => 'Фильтр каталога|Фильтры каталога',
    'product_filter_category'        => 'Категория фильтров каталога|Категории фильтров каталога',
    'product_images_update'          => 'Обновить изображения \':product\'',
    'product_information'            => 'Всё о товаре',
    'product_main_image_label'       => 'Основное изображение товара',
    'product_property'               => 'Свойство товара каталога|Свойства товара каталога',
    'product_property_new_title'     => 'Новое свойство товара каталога',
    'product_property_value_label'   => 'Занчение',
    'product_update'                 => 'Обновить товар каталога',
    'property_update'                => 'Обновить свойство \':property\'|Обновить свойства \':property\'',
    'title'                          => 'Каталог',
);