<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/category.php
// Date: 2016-09-29 14:29:00
return array(
    'new_title' => 'Новая категория',
    'update'    => 'Обновить категорию',
);