<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/category.php
// Date: 2016-10-01 12:17:15
return array(
    'new_title' => 'Новая категория',
    'update'    => 'Обновить категорию',
);