<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/category.php
// Date: 2016-10-22 11:49:45
return array(
    'new_title'          => 'Новая категория',
    'update'             => 'Обновить категорию',
    'visible_name_label' => 'Название для отображения',
);