<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/feedback.php
// Date: 2016-10-22 11:49:45
return array(
    'from_name_label'             => 'Ваше имя',
    'from_name_placeholder'       => 'Ваше имя',
    'message_content_placeholder' => 'Содержимое сообщения',
    'message_content_title'       => 'Сообщение',
    'message_update'              => 'Обновить сообщение от',
    'request_from'                => 'Запрос от',
    'sender_email_placeholder'    => 'Адерс электронной почты отправителя',
    'sender_email_title'          => 'Адерс электронной почты',
    'sender_name_placeholder'     => 'Имя отправителя',
    'sender_name_title'           => 'Отправитель',
    'title'                       => 'Обратаня связь',
);