<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/filter.php
// Date: 2016-10-04 08:32:48
return array(
    'catalog_category'     => 'Категория каталога',
    'is_filter_disabled'   => 'Фильтр отключен?',
    'left_property_label'  => 'Значение \'левого\' свойства',
    'new_title'            => 'Новый фильтр',
    'right_property_label' => 'Значение \'правого\' свойства',
    'state'                => 'Состояние фильтра',
    'title_label'          => 'Заголовок фильтра',
    'title_placeholder'    => 'Текст заголовка',
    'type_label'           => 'Тип фильтра',
    'update'               => 'Обновить фильтр',
);