<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/models.php
// Date: 2016-10-01 12:17:15
return array(
    'deleted' => 'Модель :Name удалена.',
    'edit'    => 'Редактировать :Name модель.',
    'saved'   => 'Модель :Name сохранена.',
    'updated' => 'Модель :Name обновлена.',
);