<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/models.php
// Date: 2016-10-04 08:32:48
return array(
    'deleted' => 'Запись удалена.',
    'edit'    => 'Редактировать запись :Name.',
    'saved'   => 'Запись сохранена.',
    'updated' => 'Запись обновлена.',
);