<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/pagination.php
// Date: 2016-09-29 14:29:00
return array(
    'next'     => 'Вперёд &raquo;',
    'previous' => '&laquo; Назад',
);