<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/pagination.php
// Date: 2016-10-01 12:17:15
return array(
    'next'     => 'Вперёд &raquo;',
    'previous' => '&laquo; Назад',
);