<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/passwords.php
// Date: 2016-10-01 12:17:15
return array(
    'password' => 'Пароль должен быть не менее шести символов и совпадать с подтверждением.',
    'reset'    => 'Ваш пароль был сброшен!',
    'sent'     => 'Ссылка на сброс пароля была отправлена!',
    'token'    => 'Ошибочный код сброса пароля.',
    'user'     => 'Не удалось найти пользователя с указанным электронным адресом.',
);