<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/subscription.php
// Date: 2016-09-29 14:29:00
return array(
    'is_news_subscribed'  => 'Подписаться на обновления новостей?',
    'is_posts_subscribed' => 'Подписаться на обновления блога?',
    'update'              => 'Управление подписками',
);