<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/ru/task.php
// Date: 2016-10-04 08:32:48
return array(
    'content_label'       => 'Текст задачи',
    'content_placeholder' => 'Текст задачи',
    'new_title'           => 'Новая задача',
    'title'               => 'Задачи',
    'title_label'         => 'Заголовок задачи',
    'title_placeholder'   => 'Текст заголовка',
    'update'              => 'Обновить задачу',
);